### ISSUE TITLE
Learning section 4 (Git)

### ISSUE THREAD

**Issue by zautumnz** [prolesoft/prolesoft.github.io#10]
https://try.github.io/

https://www.codecademy.com/learn/learn-git

https://tutorialzine.com/2016/06/learn-git-in-30-minutes

**Comment by aeshthetic** [comment]
This codecademy course is also no longer free :/

https://www.katacoda.com/courses/git This course seems really cool, simple and interactive!

**Comment by zautumnz** [comment]
Cool, I think maybe recommending the Github tutorial and that Katacoda link would be enough.
