### ISSUE TITLE
Learning section 5 (storage)

### ISSUE THREAD

**Issue by zautumnz** [prolesoft/prolesoft.github.io#11]
https://sqlbolt.com/ is a great online tutorial for learning SQL

https://www.postgresqltutorial.com/ is specifically for PG

https://university.mongodb.com/ teaches Mongo, requires signup, but skills are transferable to other document stores.

**Comment by aeshthetic** [comment]
I like sqlbolt a lot. Codecademy's SQL tutorial is free, but maybe at this phase it makes sense to step away from super hand-holding tutorials/resources.

**Comment by zautumnz** [comment]
I agree, if someone has made it this far I think they're ready for more self-guided learning
