### ISSUE TITLE
Consider alternative Git hosting

### ISSUE THREAD

**Issue by zautumnz** [prolesoft/prolesoft.github.io#2]
Some folks would rather not contribute on GitHub. I personally don't want to lose the accessibility of GitHub, since most people are here, but it would be good to have another space set up on a Gitea or Gogs server. We'd have to make sure they stay in sync.

**Comment by zautumnz** [comment]
@Nutomic volunteered yerbamate.dev, so marxist.space is now mirrored there, and we can set that up for other projects as they come along. https://yerbamate.dev/decadesinweeks/marxist.space

**Comment by Nutomic** [comment]
You can also make an org there ;)
