### ISSUE TITLE
Learning section 2 (Scripting)

### ISSUE THREAD

**Issue by zautumnz** [prolesoft/prolesoft.github.io#6]
Get Started, the first short book in the You Don't Know JS series: https://github.com/getify/You-Dont-Know-JS/blob/2nd-ed/get-started/README.md

The rest of this series is also good, maybe worth linking in section 6

https://eloquentjavascript.net/ is also good. I read the whole thing in about 3 days on a bus and got a lot out of it

And for Python, this site covers the basics and also has a little repl so folks don't have to mess around with installing: https://www.learnpython.org/

**Comment by aeshthetic** [comment]
As we begin this process I suggest we each take a brief look at the resources the other suggests and give a short assessment in this thread to determine a conclusion regarding whether a particular resource should be included, or whether it should be included with any notes, etc.

**Comment by aeshthetic** [comment]
Looking at eloquentjs and YDKJS(Y), I think it's important to keep in mind that section 2 will be reached relatively quickly by new programmers, and that too from a relatively simple place (HTML and CSS). The transition should be smooth and not particularly daunting.

YDKJS(Y) explicitly mentions that one must "Keep in mind that even though this book is titled "Get Started," it's not intended as a beginner/intro book," and that "This book's main job is to get you ready for studying JS deeply throughout the rest of the series; it's written assuming you already have familiarity with JS over at least several months experience before moving on in YDKJSY."

I think this alone warrants moving it to an optional resource in section 6, or perhaps rename section 8 to advanced programming concepts and include it there?

I have some concerns about how daunting eloquentjs might be for a newcomer. The bit of philosophy at the beginning may be valuable for the learning programmer to keep in mind, but the rest may be difficult to work with.

The python resource you provided is around the level I think is most appropriate for this section. We can look for similar resources on that level for JS as well.

**Comment by aeshthetic** [comment]
https://automatetheboringstuff.com/ is a personal favourite that I find really gets to the essence of what scripting is all about, and immediately sets it apart from the kind of work the learning programmer did with HTML and CSS while also providing a comfortable transition.

https://python.swaroopch.com/ is a tutorial I've used in the past that is more traditionally structured.

Both of these tutorials provide steps for installing the interpreter and an editor locally, and this might be the right section to get the learning programmer to do that.

**Comment by aeshthetic** [comment]
https://www.codecademy.com/learn/introduction-to-javascript

This course seems pretty complete. I'm not sure I'd rather have a learning programmer learn Python or JavaScript over the other, though, if that makes sense. However, I think this might be a good opportunity to show how learning one language _does_ make learning others easier in a lot of cases.

**Comment by zautumnz** [comment]
Whoever runs that LearnPython tutorial also runs others: https://www.learn-js.org/

Maybe those two + Automate The Boring Stuff optionally, since it's a bit longer? There are tbh a lot of options for learning JS, I don't want to include too many since people might get overwhelmed.

**Comment by aeshthetic** [comment]
If the learning programmer has already used codecademy for HTML and CSS, using it for javascript would probably be the most comfortable progression. After that, it might be fair to ask them to step out of codecademy's hand-holding environment and install python locally and learn it with an online book.

the Learn Python and Learn JS sites seem to be aimed at people who already know a language coming in, which is not quite ideal.
