### ISSUE TITLE
Learning section 3 (CLI)

### ISSUE THREAD

**Issue by zautumnz** [prolesoft/prolesoft.github.io#9]
This explains some of the backstory behind what the deal is with the CLI, Unix, etc: https://smorgasborg.artlung.com/C_R_Y_P_T_O_N_O_M_I_C_O_N.shtml It's long but might be worth linking as optional reading.

This has a list of CLI alternatives to GUI actions: https://github.com/you-dont-need/You-Dont-Need-GUI

Codecademy CLI course: https://www.codecademy.com/learn/learn-the-command-line

And another course: https://www.learnenough.com/command-line-tutorial/basics

**Comment by aeshthetic** [comment]
That codecademy course is no longer free, unfortunately :(

I really like learnenough. It suggests installing an ubuntu VM. This is attractive, but it might not be feasible for everyone. We might need to include some information about WSL or online environments like repl.it as an alternative.

**Comment by zautumnz** [comment]
Katacoda might be good for that

**Comment by zautumnz** [comment]
Okay how about the first link as optional reading, and [this Katacoda](https://www.katacoda.com/cybershaolin/courses/intro-to-linux/linux-commands)?

**Comment by aeshthetic** [comment]
I don't see the value of this katacoda to be honest. It demonstrates one command and then leaves you with a cheatsheet. I'll look for alternatives.

**Comment by aeshthetic** [comment]
Oh, was your intention to provide Katacoda as a space for experimenting with a shell online? I think this might be preferable:
https://www.katacoda.com/courses/ubuntu/playground

**Comment by zautumnz** [comment]
Oh sorry, I looked at the overview of that course and thought it would be more complete.

**Comment by zautumnz** [comment]
I just came across this which looks pretty neat, it's a gamified thing: https://web.mit.edu/mprat/Public/web/Terminus/Web/main.html

**Comment by aeshthetic** [comment]
This is cool. I wish the font was bigger. It seems like it doesn't really cover much more than a few basic commands? Or maybe you need to get further through the game to find out about more of them.

**Comment by zautumnz** [comment]
Looks like there's an updated version [here](http://www.mprat.org/Terminus/). It is mostly `cd` and `ls`, there's a [playthrough](https://www.youtube.com/watch?v=qwy7tY5Vs6M) here.
